# Generated by Django 3.2.18 on 2023-04-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_gameroom_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='room_number',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='room_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Room Name'),
        ),
    ]
