# Generated by Django 3.2.18 on 2023-04-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_gameroom_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='is_full',
        ),
    ]
