# Generated by Django 3.2.18 on 2023-04-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(verbose_name='Room Number')),
                ('max_players', models.IntegerField(verbose_name='Max Players')),
                ('is_full', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MagicCornerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=120, verbose_name='Game Name')),
                ('game_date', models.DateTimeField(verbose_name='Game Date')),
                ('table_host', models.CharField(max_length=60, verbose_name='Game Host')),
                ('game_description', models.TextField(blank=True)),
                ('game_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.gameroom')),
                ('players', models.ManyToManyField(blank=True, to='events.MagicCornerUser')),
            ],
        ),
    ]
