# Generated by Django 3.2.18 on 2023-04-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20230420_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='is_full',
            field=models.BooleanField(blank=True, null=True, verbose_name='Room Full'),
        ),
    ]
